### PR TITLE
make types better

### PR DESCRIPTION
**Pull request by auscyber**
I think this is reasonably sane? I don't have access to the API's so I haven't tested it, but it *should* be right if i've flattened everything correctly.

`derive_more` is to make all the Display implementations a bit simpler 

and also sorry it is a lot of code

### CODE REVIEW

**Comment by auscyber** [comment]
and also add search and first top, lemem know if you want me to split these into separate prs

**Comment by auscyber** [comment]
okay now im actually actually done, i just messed up a lot of the like blame and consistency with the commits, like it seemed like i made way more changes than i did, all good now :3

**Comment by tascord** [comment]
Looks like the checks in actions are failing. Ill have a look at this soon and get this merged in :3 . Thank you for the pr !! this is wonderful

**Comment by auscyber** [comment]
looks like the tests broke or something, error said devid wrong, it worked for me on my repo

**Comment by auscyber** [comment]
like u can see the tests on my push, maybe ur devid got invalidated?

**Comment by tascord** [comment]
Tests worked locally? Ill get this working in the ci

**Comment by tascord** [comment]
Also will do a fmt

**Pull request merged**
